name: Pull Request Stats

on:
  pull_request:
    types: [opened]

jobs:
  stats:
    runs-on: ${{ vars.DEFAULT_RUNS_ON }}
    steps:
      - name: Run pull request stats
        uses: flowwer-dev/pull-request-stats@master
